
#ifndef SZS_TEXT_LOGO_INC
#define SZS_TEXT_LOGO_INC 1

const char text_logo[] =
{
  "		*****************************************\n"
  "		*    __            __ _ ___________     *\n"
  "		*    \\ \\          / /| |____   ____|    *\n"
  "		*     \\ \\        / / | |    | |         *\n"
  "		*      \\ \\  /\\  / /  | |    | |         *\n"
  "		*       \\ \\/  \\/ /   | |    | |         *\n"
  "		*        \\  /\\  /    | |    | |         *\n"
  "		*         \\/  \\/     |_|    |_|         *\n"
  "		*                                       *\n"
  "		*           Wiimms ISO Tools            *\n"
  "		*         https://wit.wiimm.de/         *\n"
  "		*                                       *\n"
  "		*****************************************\n"
};

#endif // SZS_TEXT_LOGO_INC

