/^~/ d;
s|@.@@@|3.05a|g;
s|@@@@-@@-@@|2026-08-18|g;
s|@@:@@:@@|16:43:25|g;
s|@@AUTHOR@@|Dirk Clemens|g;
s|@@SYSTEM@@|mac|g;
s|@@SYSTEM2@@|mac/arm|g;
s|@@TOOLSET-SHORT@@|WIT|g;
s|@@TOOLSET-LONG@@|Wiimms ISO Tools|g;
s|@@WIT-SHORT@@|wit|g;
s|@@WIT-LONG@@|Wiimms ISO Tool|g;
s|@@WWT-SHORT@@|wwt|g;
s|@@WWT-LONG@@|Wiimms WBFS Tool|g;
s|@@WDF-SHORT@@|wdf|g;
s|@@WDF-LONG@@|Wiimms WDF Tool|g;
s|@@WFUSE-SHORT@@|wfuse|g;
s|@@WFUSE-LONG@@|Wiimms FUSE Tool|g;
s|@@VERSION@@|3.05a|g;
s|@@VERSION-NUM@@|3.05a|g;
s|@@BETA-VERSION@@|0|g;
s|@@BETA-SUFFIX@@||g;
s|@@REV@@|8638|g;
s|@@REV-NUM@@|8638|g;
s|@@REV-NEXT@@|8638|g;
s|@@BINTIME@@|1787089405|g;
s|@@DATE@@|2026-08-18|g;
s|@@TIME@@|16:43:25|g;
s|@@INSTALL-PATH@@|/usr/local|g;
s|@@SHARE-PATH@@|/usr/local/share/wit|g;
s|@@BIN-FILES@@|wit wwt wdf wfuse |g;
s|@@SHARE-FILES@@|titles.txt titles-de.txt titles-es.txt titles-fr.txt titles-it.txt titles-ja.txt titles-ko.txt titles-nl.txt titles-pt.txt titles-ru.txt titles-zhcn.txt titles-zhtw.txt system-menu.txt magic.txt|g;
s|@@WDF-LINKS@@|wdf-cat wdf-dump|g;
s|@@CYGWIN-DIR@@|/usr/bin|g;
s|@@CYGWIN-TOOLS@@|bash cp diff env grep mkdir mv realpath regtool rm stat tr wget|g;
s|@@WIN-INSTALL-PATH@@|Wiimm/WIT|g;
s|@@LANGUAGES@@|de es fr it ja ko nl pt ru zhcn zhtw|g;
s|@@DISTRIB-PATH@@|./wit-v3.05a-r8638-mac/arm|g;
s|@@DISTRIB-I386@@|wit-v3.05a-r8638-i386.tar.gz|g;
s|@@DISTRIB-X86_64@@|wit-v3.05a-r8638-x86_64.tar.gz|g;
s|@@DISTRIB-MAC@@|wit-v3.05a-r8638-mac.tar.gz|g;
s|@@DISTRIB-CYGWIN32@@|wit-v3.05a-r8638-cygwin64.zip|g;
s|@@DISTRIB-CYGWIN64@@|wit-v3.05a-r8638-cygwin32.zip|g;
s|@@URI-FILE@@|https://wit.wiimm.de/file|g;
s|@@URI-REPOS@@|http://opensvn.wiimm.de/wii/trunk/wiimms-iso-tools/|g;
s|@@URI-VIEWVC@@|https://wit.wiimm.de/r/viewvc|g;
s|@@URI-HOME@@|https://wit.wiimm.de/|g;
s|@@URI-DOWNLOAD@@|https://wit.wiimm.de/download|g;
s|@@URI-WDF@@|https://wit.wiimm.de/r/wdf|g;
s|@@URI-CISO@@|https://wit.wiimm.de/r/ciso|g;
s|@@URI-QTWITGUI@@|https://wit.wiimm.de/r/qtwitgui|g;
s|@@URI-WIIBAFU@@|https://wit.wiimm.de/r/wiibafu|g;
s|@@URI-MACWITGUI@@|https://wit.wiimm.de/r/mac-witgui|g;
s|@@URI-GBATEMP@@|http://gbatemp.net/index.php?showtopic=182236#entry2286365|g;
s|@@URI-DOWNLOAD-I386@@|https://wit.wiimm.de/download/wit-v3.05a-r8638-i386.tar.gz|g;
s|@@URI-DOWNLOAD-X86_64@@|https://wit.wiimm.de/download/wit-v3.05a-r8638-x86_64.tar.gz|g;
s|@@URI-DOWNLOAD-MAC@@|https://wit.wiimm.de/download/wit-v3.05a-r8638-mac.tar.gz|g;
s|@@URI-DOWNLOAD-CYGWIN@@|https://wit.wiimm.de/download/|g;
s|@@URI-TITLES@@|http://gametdb.com/titles.txt|g;
