
//---------------------------------"
// This file is generated by make."
// Any changes will be lost!"
//---------------------------------"

#define TOOLSET_SHORT	"WIT"
#define TOOLSET_LONG	"Wiimms ISO Tools"
#define WIT_SHORT	"wit"
#define WIT_LONG	"Wiimms ISO Tool"
#define WWT_SHORT	"wwt"
#define WWT_LONG	"Wiimms WBFS Tool"
#define WDF_SHORT	"wdf"
#define WDF_LONG	"Wiimms WDF Tool"
#define WFUSE_SHORT	"wfuse"
#define WFUSE_LONG	"Wiimms FUSE Tool"
#define AUTHOR		"Dirk Clemens"

#define VERSION		"3.05a"
#define VERSION_NUM	"3.05a"
#define BETA_VERSION	0

#define REVISION	"8638"
#define REVISION_NUM	8638
#define REVISION_NEXT	8638

#define BINTIME		1787088729
#define DATE		"2026-08-18"
#define TIME		"16:32:09"
#define DATETIME	"2026-08-18 16:32:09"

#define INSTALL_PATH	"/usr/local"
#define SHARE_PATH	"/usr/local/share/wit"
#define WIN_INSTALL_PATH "Wiimm/WIT"

#define URI_REPOS	"http://opensvn.wiimm.de/wii/trunk/wiimms-iso-tools//"
#define URI_VIEWVC	"https://wit.wiimm.de/r/viewvc/"
#define URI_HOME	"https://wit.wiimm.de/"
#define URI_DOWNLOAD	"https://wit.wiimm.de/download"

